### ISSUE TITLE
`Actual exit status` number shows up red if `Expected exit status` is not present.

### ISSUE THREAD

**Issue by bkayes** [eecs-autograder/autograder.io#30] opened 2022-01-18 22:13 UTC
See [this screenshot](https://cdn-uploads.piazza.com/paste/kk1jpew873f3j3/57a88ac13b67abaaf7d6d2cc19b9dabdea63817ead4f95d7ecb67b8886c0fae5/Screen_Shot_2022-01-18_at_4.21.32_PM.png) from a recently confused student in our class which shows that when the `Expected exit status` is missing, it marks the `Actual exit status` number as red, which is confusing. Ideally this number would show up as blue; since there is no expected exit status, any exit status should be correct.

**Comment by james-perretta** [comment] 2022-01-19 15:39
Good catch! 

Notes to self, the issue is here: https://github.com/eecs-autograder/ag-website-vue/blob/develop/src/components/project_view/submission_detail/ag_test_command_result_detail.vue#L35
We need to update the logic so that 'actual-return-code-incorrect' is not applied if `return_code_correct` is null.

**Comment by james-perretta** [comment] 2022-01-19 15:43
@bkayes To help prevent additional confusion until this fix gets done and deployed, you might consider setting "expected return code" to zero for that part of the test case.

**Comment by broad-well** [comment] 2024-03-31 02:45
@james-perretta, @Normanwqn and I would like to work on this issue (and potentially more issues here) as part of our coursework for [EECS 481](https://eecs481.org/hw6.html), Software Engineering. Our work will be in [my fork](https://github.com/broad-well/ag-website-vue).

**Comment by james-perretta** [comment] 2024-04-01 14:06
@broad-well @Normanwqn All yours!

**Closed** 2024-09-13 14:25 UTC
Labels: bug
